app <- ShinyDriver$new("../../")
app$snapshotInit("UI_tests")

app$snapshot()
app$setInputs(link_to_ind_by_subj_tab = "click")
app$snapshot()
app$setInputs(selectType = "SustainedEmploymentPercent")
app$snapshot()
app$setInputs(selectProvision = "Apprenticeship")
app$snapshot()
app$setInputs(selectSSA = "Agriculture, Horticulture and Animal Care")
app$snapshot()
app$setInputs(selectSSATier2 = "Agriculture")
app$setInputs(selectSSATier2 = "Animal Care and Veterinary Science")
app$snapshot()
app$setInputs(selectBreakdown = "Ethnicity")
app$snapshot()
app$setInputs(selectSSA = "All")
app$setInputs(selectProvision = "All")
app$setInputs(selectType = "NumberSustainedEmployment")
app$snapshot()
app$setInputs(selectBreakdown = "LevelOfLearning")
app$snapshot()
app$setInputs(selectBreakdown = "Gender")
app$snapshot()
app$setInputs(navlistPanel = "SubjectByIndustry")
app$snapshot()
app$setInputs(selectTypeSubj = "SustainedEmploymentPercent")
app$snapshot()
app$snapshot()
app$setInputs(selectIndustry = "Accommodation and food service activities")
app$setInputs(selectSSADetail = "SSATier2")
app$snapshot()
app$setInputs(selectProvisionSubj = "Apprenticeship")
app$snapshot()
app$setInputs(selectBreakdownSubj = "Ethnicity")
app$setInputs(selectIndustry = "All")
app$snapshot()
app$setInputs(selectBreakdownSubj = "LevelOfLearning")
app$snapshot()
app$setInputs(selectBreakdownSubj = "Gender")
app$snapshot()
