on:
  push:
    branches:
      - main
      - development
      
name: deploy-shiny


jobs:
  deployShiny:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        # Running on mac as it's quicker to build
          - {os: macOS-latest, r: '4.2.3'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      RENV_PATHS_ROOT: ~/.local/share/renv
      SHINYAPP_NAME: undefined

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set env vars (dev)
        if: endsWith(github.ref, '/development')
        run: |
          echo "SHINYAPP_NAME='dev-obsm-industry'" >> $GITHUB_ENV
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/main')
        run: |
          echo "SHINYAPP_NAME='obsm-industry'">> $GITHUB_ENV

      - id: deploy
        name: Deploy to shinyapps.io
        uses: qwert666/shinyapps-actions@main
        env:
            SHINY_USERNAME: 'department-for-education'
            SHINY_TOKEN: ${{ secrets.SHINYAPP_TOKEN }}
            SHINY_SECRET: ${{ secrets.SHINYAPP_SECRET }}
            APP_NAME: ${{env.SHINYAPP_NAME}}
            APP_DIR: ''
          
